version: '3.8'

services:
  # 1. BACKEND SERVİSİ
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: pet_backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./app/backend:/app      # Canlı kodlama için
      - ./models:/app/models    # Modeller için (DIŞARIDAN GELECEK)
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=-1
      - PYTHONUNBUFFERED=1
    networks:
      - pet_network

  # 2. FRONTEND SERVİSİ
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: pet_frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    volumes:
      - ./app/frontend:/app   # Canlı kodlama için
    env_file:
      - .env
    environment:
      - API_URL=${API_URL:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - pet_network

networks:
  pet_network:
    driver: bridge
