# params.yaml
train:
  epochs: 10
  batch_size: 32
  learning_rate: 0.0001
  img_size: 224
  embedding_dim: 128
  alpha: 0.2          # Triplet Loss marjı
  loss_weight: 2.0    # Triplet Loss ağırlığı
  steps_per_epoch: 50 # Senin kodunda 50 olarak sabitlenmiş
  data_path: "data/train"
  model_output: "models/experimental_model.weights.h5"